import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "./theme-provider";
import { TailwindIndicator } from "@/components/ui/tailwind-indicator";
import StoreProvider from "./store-provider";
import { QueryProvider } from "./query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          <SessionProvider>
            <StoreProvider>
              <QueryProvider>{children}</QueryProvider>
            </StoreProvider>
          </SessionProvider>
        </ThemeProvider>
        <TailwindIndicator />
      </body>
    </html>
  );
}
